p0-security/p0cli

package.json, yarn.lock
Running p0 after npm install -g currently fails due to semver module not found.
=> Add semver to package.json to fix npm install

src/commands/__tests__/__snapshots__/ssh.test.ts.snap, src/commands/ssh.ts
This PR updates the ssh session cli command from `ssh <destination> --provider ...` to `ssh session <destination> --provider ...`
This is required due to changes from https://github.com/p0-security/app/pull/1514
=> Update ssh session cli command

src/commands/__tests__/request.test.ts, src/commands/__tests__/ssh.test.ts, src/commands/request.ts, src/commands/ssh.ts, src/types/request.ts
This PR allows users to connect to nodes that have been granted group approval.
=> Users can start a session for nodes with a group approval

src/commands/__tests__/request.test.ts, src/commands/__tests__/ssh.test.ts, src/commands/request.ts, src/commands/ssh.ts, src/plugins/aws/ssm/index.ts, src/plugins/aws/types.ts, src/types/request.ts, yarn.lock
In a [different PR for our app](https://github.com/p0-security/app/pull/1526) the permission spec for `ssh sessions` has changed. This change was required to support requesting access to a group of nodes.
=> Add support for p0 request ssh group <name>

src/commands/index.ts
This was accidentally hard-coded to the lodash version. Instead use the package.json version (this is the yargs default, so we get this behavior merely by deleting existing code).
=> Fix version command

package.json, src/commands/__tests__/ssh.test.ts, src/commands/ssh.ts, src/plugins/ssh/types.ts
Addresses: ENG-1766
updates ssh installation to check for new installation document structure
=> Support migrated ssh integration

src/commands/aws/__tests__/__snapshots__/role.test.ts.snap, src/plugins/aws/__mocks__/assumeRole.ts, src/plugins/aws/assumeRole.ts, src/plugins/aws/types.ts
`AWS_SECURITY_TOKEN` is the legacy version of `AWS_SESSION_TOKEN`. 
It does seem to take precedence over `AWS_SESSION_TOKEN`. 
The okta-aws-cli sets both: https://github.com/okta/okta-aws-cli/blob/f1e09eab509e295a7e7b3002d14f2a96b8c60914/internal/output/envvar.go#L49L63
This causes an issue where if someone uses the okta-aws-cli to log in and then uses p0, the environment variables end up in  an inconsistent state.
=> Set AWS_SECURITY_TOKEN environment variable

src/plugins/aws/ssm/index.ts
This PR introduces a new method of executing our SCP command. Our previous method accidentally included the ssh key in the name which accidentally revealed the private key. This new method starts a `bash` process and then pipes in the `scp` command through `stdin` preventing the private key from being revealed. We're also unsetting that subcommands history, this should prevent anyone who somehow gains access to that subcommand from searching for the private key in the command history.
=> Do not allow private key to appear in bash history or process logs

src/commands/scp.ts, src/commands/shared.ts, src/plugins/aws/ssm/index.ts
This PR enables a debug mode for SCP that:
- displays information about the `ssh-agent`
- prints the private key that will be used to connect to the requested node.
- provides manual commands to run for local testing.
**Sample Command**
```
p0 scp 10mb.txt clone-node-2:10mb.txt --debug
```
=> Add debug mode for scp

package.json, src/plugins/aws/ssm/index.ts
Our implementation of scp requires that we spin up a special agent to store ephemeral private keys in. We'll lose access to the local `ssh-agent` if a user overrides the identity agent using their config settings in either `/etc/ssh/ssh_config` or `~/.ssh/config`.
**Example config**
```
Host *
IdentityAgent "~/X/Y/Z/agent.sock"
```
Command line options have the highest precedence. By adding a `-o` argument we prevent users from overriding this setting.
=> Do not allow user ssh settings to override the identity agent

src/commands/login.ts, src/plugins/login.ts, src/plugins/oidc/login.ts, src/plugins/okta/login.ts, src/plugins/ping/login.ts, src/types/org.ts, src/util.ts
Adds support for logging in with Ping Identity (Tested with PingOne)
The flow from Okta can be entirely reused.
The first commit shows the actual code changes by editing `src/plugins/okta/login.ts` in place.
The second commit is a pure code move to extract the shared functions + addition of a missed copyright header.
(Third commit is code formatting.)
=> Ping Identity OIDC login

src/commands/allow.ts, src/commands/index.ts, src/types/allow.ts
Adds a new command to the CLI which allows users to execute `p0 allow`. It inherits the options of the request we're attempting to grant standing access to.
=> Add support for p0 allow

src/commands/__tests__/ssh.test.ts, src/commands/shared.ts, src/plugins/aws/ssm/index.ts, src/plugins/aws/types.ts
This PR removes any mention of the generated ssm document, we're no longer relying on our custom generated documents for this.
=> Remove generated ssm document

src/commands/__tests__/__snapshots__/ssh.test.ts.snap, src/commands/__tests__/ssh.test.ts, src/commands/scp.ts, src/commands/shared.ts, src/commands/ssh.ts, src/common/__mocks__/keys.ts, src/common/keys.ts, src/drivers/api.ts, src/index.ts, src/plugins/aws/ssm/index.ts, src/plugins/aws/types.ts, src/plugins/ssh-agent/index.ts, src/plugins/ssh-agent/types.ts
This PR removes the ephemeral keys and exercise-grant endpoint. Instead a pair of keys will be generated and stored in the `.p0` folder. These keys will be used every time you access a node. These keys are automatically inserted into a users running agent. If an agent is not running, they will receive an error message telling them to start one.
New SSH debug commands:
1. Perform a regular ssh access request: `p0 ssh private-node --sudo`
1. Perform a request with SCP using: `p0 scp private-node:10mb.txt test.txt`
1. Add a few keys to your agent using `ssh-add`.
2. Ssh into target machine with agent forwarding argument: `p0 ssh private-node -A`
3. Run `ssh-add -l` from target machine and verify that ssh-agent was forwarded.
1. Run `pgrep -x ssh-agent` to find your ssh agents.
2. Run `eval …
=> Use persistent keys for granting ssh access

package.json, src/commands/__tests__/ssh.test.ts, src/commands/request.ts, src/commands/scp.ts, src/commands/shared.ts, src/commands/ssh.ts, src/common/subprocess.ts, src/plugins/aws/ssh.ts, src/plugins/aws/ssm/index.ts, src/plugins/aws/types.ts, src/plugins/google/ssh-key.ts, src/plugins/google/ssh.ts, src/plugins/google/types.ts, src/plugins/ssh-agent/index.ts, src/plugins/ssh/index.ts, src/types/request.ts
Support ssh with gcloud using native ssh with public key authentication and ProxyCommand - the same way as the existing AWS ssh works.
The underlying ProxyCommand in gcloud's case is `gcloud compute start-iap-tunnel`. The IAP tunnel is necessary for accessing VMs without an external IP.
All of the existing SSH functionality is supported: `-A`, `-N`, `-L`, `--sudo`, and `scp`.
However, login to Google Cloud is separate from `p0 login`. There is no support for automatic log in to Google Cloud with SAML (or other way). If we detect that the issue is gcloud login we print `Please login to Google Cloud CLI with 'gcloud auth login'`
- Rename variables and rewrite comments to apply to both AWS and GCP
- Rework types to more closely resemble backend types and share common fields
- Add detection …
=> Basic gcloud ssh

package.json, yarn.lock
Addresses https://github.com/p0-security/p0cli/security/dependabot/6.
Also add `packagemanager` field to package.json to meet corepack requirements (as added automatically by yarn).
=> dependencies: Bump jsdom version

src/commands/__tests__/__snapshots__/grant.test.ts.snap, src/commands/__tests__/grant.test.ts, src/commands/grant.ts, src/commands/index.ts, src/commands/shared/request.ts, src/commands/shared/ssh.ts
The P0 backend supports `p0 grant`. Wire this up in the CLI.
I moved code shared between "grant" and "request" commands to `src/commands/shared/request`.
=> grant: Add command

package.json, src/commands/shared/ssh.ts, src/plugins/aws/ssh.ts, src/plugins/google/ssh.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
Previously, we were not able to verify if sudo access has propagated to Google Cloud VMs, specifically in the case when the user already had regular access and then requested sudo access. This is because the IAM permissions for regular access already exist, so we successfully logged in the user to the VM. However, the new IAM permissions to allow sudo have not propagated yet, so the user was not able to successfully execute any sudo commands until later.
This PR addresses the issue by executing a pre-test ssh command that runs `sudo -v` in non-interactive mode to verify that the user _can_ sudo. Once the test completes we go on to log the user in.
Also refactors code to move aws and gcloud checks from `plugins/ssh/index.ts`.
Completes ENG-2292
=> Pre-test for sudo in gcloud ssh

package.json, src/commands/aws/files.ts, src/commands/index.ts, src/commands/kubeconfig.ts, src/commands/shared/index.ts, src/common/install.ts, src/drivers/stdio.ts, src/plugins/aws/ssm/install.ts, src/plugins/kubeconfig/index.ts, src/plugins/kubeconfig/install.ts, src/plugins/kubeconfig/types.ts, src/types/request.ts, src/util.ts, yarn.lock
This PR implements support for fully automated access to an AWS EKS cluster for AWS accounts configured to use IAM Identity Center or federated access via Okta SAML. The command, `p0 kubeconifig` will:
- Confirm that required tooling, specifically the AWS CLI and `kubectl`, are installed, and provide installation assistance if not
- Make a P0 request to the given cluster and wait for access to be granted
- If using IDC, perform an SSO login to IDC
- For both IDC and federated, write the temporary AWS credentials to a profile in the `~/.aws/credentials` file, using a unique but stable profile for each EKS cluster to allow for re-running the command to refresh credentials
- Makes use of an INI parser and atomic file writes to guard against corruption issues and prevent stomping on other …
=> Add command for automated access to EKS clusters

src/commands/shared/ssh.ts, src/commands/ssh.ts, src/plugins/ssh/index.ts
Update P0 CLI to include SSH -o (options) and -R (remote port forwarding) options
Manually verified that P0 SSH now works to enable remote port forwarding for dev instance on both AWS and GCP.
=> ENG-2493 Add SSH -o and -R options

src/commands/scp.ts, src/commands/shared/ssh.ts, src/commands/ssh.ts, src/common/install.ts, src/plugins/aws/ssh.ts, src/plugins/aws/ssm/install.ts, src/plugins/google/install.ts, src/plugins/google/ssh.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
Add a new `ensureInstall` method to the SSH provider type. Move the AWS SSM installation to this function, and add a new implementation for GCP that installs the gcloud CLI.
The `ensureInstall` method must be called before any other functions on the SSH provider because those functions may already use the required dependencies. In the case of GCP, the `toCliRequest` function calls `gcloud auth print-access-token`.  Add a new `prepareRequest` function is to establish the correct ordering of calls.
https://github.com/user-attachments/assets/ed96f7f4-cc34-4563-9683-c43cb21900c1
Also: logging improvement in access propagation guard: log first attempt, and log whether it's a pre-test (used only by gcp) or actual ssh session login.
=> Automatic gcloud CLI installation

src/common/subprocess.ts
Add an error handler when invoking spawn, to handle the case where the command fails (e.g. if the program is not installed).
=> ENG-2437: Add error handler for spawn function

src/plugins/ssh/index.ts
Specify the path to the keyfile when invoking ssh and scp.
This is to avoid the "Too many authentication failures" that may happen when SSH has to iterate over too many keys before finding a match when attempting to connect.
See the ticket for additional details.
=> ENG-2319 Specify the path to the keyfile when invoking ssh and scp.

src/commands/ls.ts
Set yargs help to false in order to forward --help argument to P0 backend to correctly display ls help
Before:
```
komal@Komals-MacBook-Pro p0cli % ./p0 ls ssh --help
p0 ls [arguments..]
List request-command arguments
Options:
--help       Show help                                               [boolean]
--version    Show version number                                     [boolean]
--arguments                                              [array] [default: []]
```
After
```
komal@Komals-MacBook-Pro p0cli % ./p0 ls ssh --help
p0 ls ssh
Secure Shell (SSH)
Commands:
p0 ls ssh session <destination>  Secure Shell (SSH) session
p0 ls ssh all                    Secure Shell (SSH) all
p0 ls ssh group [name]           Secure Shell (SSH) Group
Options:
--help  Show help …
```
=> Fix ls help

package.json, src/drivers/env.ts, src/util.ts
Addresses: ENG-2527
Adds a way to segregate development and production environments based on .env configuration.
add the below line in .env file
```
P0_ENV=development
```
Folder used for environments:
production --> ./p0
example:
development -->./p0-development
stage-> ./p0-stage
=> Segregate P0 CLI local files by environment

src/commands/scp.ts, src/commands/shared/ssh.ts, src/commands/ssh.ts, src/plugins/ssh/index.ts
Support specifying any SSH option via --, e.g.:
p0 ssh dev-instance-fabian-joya --provider gcloud -- -NR '*:8080:localhost:8088' -o 'GatewayPorts yes'
Verified that both SSH and SCP work as expected, with and without --.
=> ENG-2490 Support any SSH option via --

src/plugins/ssh/index.ts, src/util.ts
Adds a delay between retries of the SSH command, to avoid "Exceeded Max Startups" and other connection errors:
debug1: kex_exchange_identification: banner line 0: Exceeded MaxStartups
=> ENG-2414 Add retry delay between SSH commands

src/plugins/ssh/index.ts
This is an attempt to resolve the "MaxStartups exceeded" error which happens when too many failed authentication attempts are made to establish an SSH connection.
Testing notes:
I was able to repro this issue before increasing the delay, and not after.
=> ENG-2685 Increase the retry delay between SSH invocations

src/plugins/google/ssh-key.ts
Improved the error-handling if 'gcloud auth print-access-token' does not return a valid access token.
=> ENG-2677 Better error-handling of expired token

src/commands/__tests__/login.test.ts, src/drivers/auth.ts
If there are multiple users with the same email in Identity Platform for a particular tenant, an authentication attempt to firebase will return a user with an empty email.
On the frontend we display an error message when that happens:
https://github.com/p0-security/app/blob/5237e1a54597dc63258e56566353ad09ecd3e187/frontend/src/components/Login/hook.ts#L301-L306
But on the CLI we had no such check.  This PR adds the same check as on the frontend.  Now when a user logs in, if they have multiple identities in Identity Platform they will see the message `Can not sign in: this user has previously signed in with a different identity provider.\nPlease contact support@p0.dev to enable this user.`
https://github.com/user-attachments/assets/7d5f94f5-199f-4ec1-96d2-ef73d1802787
=> Throw error message if user has no email from firebase

src/commands/__tests__/ls.test.ts, src/commands/kubeconfig.ts, src/commands/ls.ts, src/commands/shared/request.ts, src/drivers/__mocks__/stdio.ts, src/drivers/ansi.ts, src/drivers/stdio.ts
Currently, we provide no user feedback whilst we contact the P0 backend. This makes it difficult for the user to distinguish between waiting on a backend response and a hung process.
Use a yarn-style Unicode spinner to indicate that the process is still live.
https://github.com/user-attachments/assets/bd58acc0-7d1a-4058-a41a-d95c3c13a929
=> Print spinners during backend interaction

src/plugins/aws/ssh.ts, src/plugins/google/ssh.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
For maintainability, anything CSP-specific for SSH should be contained within the CSP's SSH provider object.
I also sorted the provider properties.
=> refactor: Separate CSP-specific functionality from generic SSH code

package.json, src/commands/__tests__/ssh.test.ts, src/plugins/aws/ssh.ts, src/plugins/aws/types.ts
The P0 backend moved IDC data from the `generated` field on the request object to the `permission` field.
Update CLI to match this format.
=> SSH: Update to work with newest IDC request format

package.json, src/plugins/aws/ssh.ts, src/plugins/google/ssh.ts, src/plugins/ssh/index.ts
* If debug is not enabled, it will now still print selected SSH output to stderr:
- "Authenticated to" ... message
- "port forwarding failed" messages
- "Sorry, user {user} may not run sudo..." messages (on pre-test only)
* Print an error message when SSH pre-test fails.
Examples:
./p0 ssh dev-instance-fabian-joya --provider gcloud -- -NR '*:8080:localhost:8088' -o 'GatewayPorts yes'
Authenticated to dev-instance-fabian-joya (via proxy) using "publickey".
Warning: remote port forwarding failed for listen port 8080
./p0 ssh dev-instance-fabian-joya --sudo        
Failed to establish an SSH session. Use the --debug option to see additional details.
=> ENG-2660: Print selected SSH output to stderr

src/commands/login.ts, src/drivers/auth.ts
This PR clears the identity cache on reauth, this helps prevent stale identities from being assumed. This typically causes problems when requesting access because the new user is granted access while the old user identity is used to make the SSH connection which fails.
=> Clear identity cache when a user re-authenticates with p0

src/commands/login.ts
This PR removes a minor optimization which was causing an endless recursive loop, every time a user logs in we'll reset their identity cache.
=> always clear identity cache when logging in

package.json, src/commands/kubeconfig.ts, src/plugins/aws/__tests__/utils.test.ts, src/plugins/aws/utils.ts, src/plugins/kubeconfig/index.ts, src/plugins/kubeconfig/types.ts
This PR unbreaks the `p0 kubeconfig` command. Some values and structures got changed around in the k8s integration config and responses from the backend:
- Required AWS IDC metadata is no longer found in the `eksGenerated` object; it's now in `awsResourcePermission`
- AWS account ID is no longer stored separately in the k8s integration configuration, and now is extracted from the EKS cluster ARN
- `provider` was renamed `hosting` in the k8s integration configuration
It also adds some minor quality-of-live improvements to the `p0 kubeconfig` command, such as utilizing `spinUntil()` for some of the longer `await`s, and adds a more robust and reusable simple AWS ARN parser.
Added a unit test for the ARN parser, and tested everything locally in both AWS IDC and AWS Federated (Okta SAML) …
=> [ENG-2790] Fix broken p0 kubeconfig command

src/commands/__tests__/login.test.ts, src/drivers/auth.ts, src/drivers/config.ts, src/drivers/firestore.ts
Fixes the error that is shown when no identity file is present.
The CLI now again shows a message asking the user to login:
./p0 ls gcloud role oauth
Please run `p0 login <organization>` to use the P0 CLI.
Added unit test.
=> ENG-2931 Fix error when no identity file is present

src/commands/login.ts, src/drivers/config.ts, src/drivers/firestore.ts
Reads the ssoProvider for login from the host specified in the config, instead of defaulting to p0-prod.
=> ENG-2960 Read ssoProvider from config host, not p0-prod

src/commands/__tests__/__snapshots__/ls.test.ts.snap, src/commands/ls.ts
I'd broken this in #42. Fix whitespace.
Before:
```
Showing the first 15 destinations (use `p0
ls ssh session destination <like>` to narrow results). Resources labeled with * are already accessible to you:
```
After:
```
Showing the first 15 destinations (use `p0 ls ssh session destination <like>` to narrow results).
Resources labeled with * are already accessible to you:
```
=> ls: Fix listing help formatting.

src/commands/shared/ssh.ts, src/common/install.ts, src/plugins/azure/install.ts, src/plugins/azure/ssh.ts, src/plugins/azure/types.ts, src/types/ssh.ts
This PR represents the start of work on Azure SSH in the P0 CLI. It adds a basic shell of an `azureSshProvider` that is the bare minimum needed to start development work, and implements automated installers for both Homebrew (required for installing the Azure CLI on macOS) and the Azure CLI (`az`) itself, and a simple call to `az login` to log in to Azure when `p0 ssh --provider azure` is invoked.
Testing requires rebasing this branch on the `azure-ssh-dev-base` branch (or cherry-picking that branch on top of this one), which contains the scaffolding currently necessary to invoke Azure SSH.
Tested the Homebrew and `az` installers locally by setting my `PATH` to not include `/opt/homebrew` (which covers `az` as well) and then running `./p0 ssh --provider azure test`. Answering "no" to the …
=> Initial Azure SSH work; login and installer

src/commands/shared/ssh.ts, src/commands/ssh.ts
This PR updates the ssh command argument `account` to use the new shared name: `parent`. The parent argument unifies inputs of `accountId` for AWS, `projectId` for Google Cloud, and `subscriptionId` for Azure.
=> update ssh command arguments to use shared properties

src/commands/ls.ts
Addresses ENG-2998. Improves CLI usability when there are a large number of results by giving the user an idea of the total number of results for their query. We request twice the requested size, and if the total number of results is within the amount, we display the number of remaining results. If not, we just display 'of many'
=> ls: display number of items that were truncated 

src/commands/shared/ssh.ts, src/plugins/azure/auth.ts, src/plugins/azure/keygen.ts, src/plugins/azure/ssh.ts, src/plugins/azure/tunnel.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
This PR improves the Azure SSH debugging experience by adding reproduction commands for Azure SSH, which are displayed when invoking `p0 ssh` with the `--debug` option. It outputs all the `az` commands, as used by the P0 CLI, that are needed to manually reproduce the SSH connection process, as well as the final `ssh`/`scp` command too. I also included some minor refactoring which both made the implementation easier, as well as removed some redundancy from the `ssh` options we end up passing for Azure SSH (e.g., previously, we technically specified two separate private keys to `ssh`, the usual P0 CLI-managed key as well as the ephemeral SSH certificate private key generated by `az ssh cert`).
The first commit also includes removing a TODO for ENG 3129, which is no longer required and …
=> Implement reproCommands for Azure SSH

src/plugins/azure/auth.ts, src/plugins/azure/keygen.ts, src/plugins/azure/ssh.ts, src/plugins/azure/tunnel.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
This PR improves the Azure SSH debugging experience by adding debug output for the various `az` commands being run before opening the `ssh`/`scp` session. Specifically, when the `--debug` flag is set, the CLI will output the stdout and stderr for all the `az` commands it runs. Note though that it _won't_ set the `--debug` flag for the `az` commands themselves as this outputs far too much information, with the exception of the `az network bastion tunnel` command; while it still outputs far too much information in debug mode, it has an unfortunate tendency to hide certain errors unless you pass it the `--debug` flag, so I did add it there.
Some additional information is also logged by the CLI itself now when the `--debug` flag is set.
Tested locally against my Azure VM in our test tenant, …
=> Add debugging output for Azure SSH provider

package.json
Bump P0 CLI version number from `0.12.0` to `0.13.0` in prep for new release
=> Bump P0 CLI version number in prep for new release

src/plugins/azure/ssh.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
This PR implements Azure's `preTestAccessPropagationArgs` and adds a new parameter to the `SSHProvider` type to support valid access errors. 
Sudo access to an azure node can sometimes take an unexpectedly long time to propagate fully and if a user connects before sudo access propagates then they'll need to restart their session in order to pick up the sudo access. Therefore it is necessary to validate sudo access before letting a user complete their connection. 
We get an error code of 1 instead of an error code 0 after sudo access is granted when performing the pretest for an Azure instance. This means that we needed to extend the `SSHProvider` interface a little to include potentially valid error messages and override the error code of 1.
> In the case a user doesn't have sudo access, …
=> Add sudo propagation check for azure

src/plugins/azure/auth.ts, src/plugins/azure/ssh.ts
This PR adds runs the `az logout` before logging in so that we wipe any currently connected identities. This resolves a handful of issues we're seeing for example: 
1. granting a user access, relinquishing access, and then granting again will use an old cached identity which will have a temporary block on access.
2. granting sudo access, and regular user access and relinquishing one temporarily blocks access to the account.
3. if someone runs `az login` and uses a different identity that has the same subscription id.
=> Azure SSH: clear current identity before logging in again

src/plugins/ssh/index.ts
We recently introduced `validAccessPatterns` in #147 which checks to make sure a certain termination string exists when performing propagation checks. Consequentially for Azure, when we exit the terminal we're now always attempting to verify that an ephemeral access message is valid and failing the check.
Two fixes were possible, 1) we either only check `isValidError` if we're in a propagation check or 2) we default `isValidError` to true and we only set it to false if we encounter an error.
We didn't go with the first option in #147 because we want to remove the concept of `isAccessPropagationPreTest` from the `accessPropagationGuard`, but checking for valid error messages should only apply during the pretest phase. This PR instead only passes `validAccessPatterns` if we're performing a …
=> Allow ctrl+d to exit terminal when valid access patterns exist

src/plugins/azure/ssh.ts
Azure user access is subject to significant propagation delays of up to 10 minutes when elevating access to sudo. If the user starts with sudo access, there is no propagation delay. The typical time for propagation is less than 1 minute, but we want to be safe, so we set the timeout to 3 minutes. With a longer timeout a user doesn't have to retry the command too many times.
=> Increase the propagation timeout for Azure SSH

package.json, src/plugins/azure/auth.ts, src/plugins/azure/types.ts
This PR applies a small refactor that improves the error handling of during auth steps for the Azure SSH plugin. When a user cancels their login attempt or if we fail to set the users active Azure subscription. The refactor introduces a knew `KnownError` type and a utility method `normalizeAzureCliError` that should make it easy to extend and capture new errors as we discover them.
=> Azure SSH: provide user friendly error messages

src/plugins/azure/auth.ts
Improved error logs when normalizing known errors so that `--debug` prints something meaningful.
=> Azure SSH: Print errors during log in attempts when debugging

src/drivers/config.ts, src/drivers/env.ts, src/plugins/google/login.ts, src/types/org.ts
The `google` object in the tenant config contains the Client ID and Client Secret.
This config is then stored in plain text in the user's home directory.
Although the Client Secret is not really a secret, storing it in plain text gives the impression that the P0 CLI is not secure.
This PR renames the `clientSecret` to `publicClientSecretForPkce` and adds more explanation in code comments. (Although these comments are not visible in the saved `config.json` file.)
The PR also makes the `google` parameters optional so this becomes a non-issue for organizations with different login methods like Okta, Ping, etc.
User-friendly error if the organization is configured with Google login but the OAuth parameters are missing:
Saved config without `google` object if the org is not configured with …
=> Make Google OAuth client parameters optional

package.json, src/plugins/ssh/index.ts
The -r (recursive) option was always applied to the scp command, even when not specified.
=> ENG-3570 Fix scp -r (recursive) option

src/commands/login.ts
This PR adds an additional check to the frontend that will automatically log a user out if they aren't authorized to access that tenant or that tenant doesn't exist. This helps prevent a poor user experience if the user mistyped the org Id or tried to access an org they are no longer a part of.
=> Validate tenant access

.vscode/launch.json, src/commands/index.ts, src/commands/shared/request.ts, src/commands/shared/ssh.ts, src/commands/ssh-proxy.ts, src/commands/ssh-resolve.ts, src/drivers/env.ts, src/plugins/aws/ssh.ts, src/plugins/azure/ssh.ts, src/plugins/google/ssh.ts, src/plugins/okta/aws.ts, src/plugins/ssh/index.ts, src/types/ssh.ts, src/util.ts
This is to allow users to run
`ssh <node-name>` rather than `p0 ssh <node-name>`
It adds two commands to the cli, `ssh-resolve` and `ssh-proxy` meant to be used in an ssh config such as the following
```
Match exec "p0 ssh-resolve %h -q"
Include .p0/ssh/configs/*.config
```
`ssh-resolve` checks if the resource exists in p0 and if the user has `approved` access to it.  If so it sets up any needed keys and writes an ssh config to `.p0/ssh/configs/` as well as request information to a temporary file, and returns 0 (success). Otherwise it returns 1 (silently if `--quiet` is passed)
`ssh-proxy` is invoked as the `ProxyCommand` by `ssh` when the config file generated by `ssh-resolve` is used, and reads the files written by `ssh-resolve` (and passed to it as cli args) and runs the relevant proxy …
=> ssh-resolve and ssh-proxy

src/commands/ssh-resolve.ts
This PR fixes a small bug where using `p0 ssh <hostname>` results in invalid host name detection when the `ssh proxy` is set up in your ssh config file.
=> Resolve: Include host in generated files

package.json, src/drivers/firestore.ts, src/plugins/login.ts
If the SSO provider is "google-oidc", the p0 login command currently fails. This PR ensures that the login flow works correctly, and that accounts using "google-oidc" as the login provider can login successfully.
=> ENG-3667 Support google-oidc login

src/plugins/google/login.ts
There is currently a bug that creates a user with a blank email in firestore when a user logs in for the first time.
This blank user breaks all subsequent logins.
I found that adding the email scope to the request for the OIDC token to google fixes this issue.  With this change logging in with the CLI creates a user with my email.
https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters
>If the email scope value is present, the ID token includes email and email_verified claims.
=> Add email to google openid scope

src/commands/aws/role.ts
Fixes issue where the AWS account id was not accepted by the `p0 aws assume role` command.
=> ENG-4294 Correctly pass in account id to assumeRoleWithOktaSaml

.github/workflows/semgrep.yml, src/commands/aws/role.ts, src/plugins/okta/aws.ts
Move common Okta SAML-related functions to okta/aws.ts. This is in preparation for adding a new `p0 aws assume permission-set` command.
=> ENG-4099 Move Okta SAML-related functions to okta/aws.ts

package.json, src/commands/aws/index.ts, src/commands/aws/permission-set.ts, src/commands/aws/role.ts, src/drivers/firestore.ts, src/index.ts
* Fixes an issue that prevented users from using the CLI if they do not already have an existing config.
* Removed unnecessary authentication call.
* Updated error handling for '/p0 aws role assume' and '/p0 aws permission-set assume' if user does not have an existing config.
* Removed superfluous demandCommand() calls.
* Verified behavior by executing aws, ls & ssh commands with/without config.
=> ENG-4566 Fix issue with CLI config/auth

src/commands/ssh-proxy.ts, src/commands/ssh-resolve.ts
Hides `p0 ssh-proxy` and `p0 ssh-resolve` commands in the help
=> Hide `p0 ssh-proxy` and `p0 ssh-resolve` commands in the help

__mocks__/@firebase/auth.ts, package.json, src/commands/__tests__/login.test.ts, src/commands/login.ts, src/drivers/auth/index.ts, src/drivers/firestore.ts, src/plugins/email/login.ts, src/plugins/login.ts, src/types/oidc.ts, src/types/org.ts
Add support for email / password login to P0 backend.
The email and password are provided by the user via the `P0_EMAIL` and `P0_PASSWORD` environment variables to avoid storing these in the cached identity file.
If an org uses password login then their "login" is the same as authenticating to firebase. That, however is not deduplicated. `loadCredentialsWithAutoLogin` and `authenticateToFirebase` both sign in the user with email / password to firebase. Although this is redundant, keeping that logic makes the change much smaller and easier to see that existing functionality is not affected.
Manually tested the following cases:
- The P0_ORG environment variable continues to work
- Google login to P0 + AWS SSH access using AWS Identity Center with Okta
- email / password login + AWS SSH …
=> Password login

package.json, src/commands/aws/__tests__/__snapshots__/role.test.ts.snap, src/commands/aws/permission-set.ts, src/commands/aws/role.ts, src/commands/aws/util.ts
The printAwsCredential() function was iterating over any field in the AwsCredential object, which include an extra `expiresAt` field used for only for caching.
Instead, changed it to print only the specific field values that contain the credentials.
=> Print only AWS credentials on `p0 aws permission-set assume` command

src/commands/index.ts, src/commands/ssh-resolve.ts
* Skip version check for ssh-resolve and ssh-proxy commands
* Suppress ssh-resolve output if host is not managed by P0
=> ENG-4653 Suppress ssh-resolve output if host is not managed by P0

package.json, src/drivers/api.ts, src/index.ts
Changes the User-Agent header to report `P0 CLI/version` when making calls to the P0 backend. This is to aid with auditing.
=> Change the User-Agent to report P0 CLI/{version}

package.json, src/index.ts
For a new release with the MacOS CLI .pkg distribution
=> Bump CLI to v18.4.0

README.md, sea-config.json, src/commands/index.ts, src/drivers/api.ts, src/index.ts, src/middlewares/version.ts, src/version.ts
Running `p0 --version` using the standalone CLI prints "unknown". This is likely due to yargs' default --version parser not being able to locate package.json. That + a few other fixes.
- Makes it so the version in package.json is the source of truth (no need to change it in multiple places)
- Add a function that identifies the version in all environments
- Use this implementation everywhere we need the version number
- Fix a potential bug where the auto-update message may not display
- Improve docs and messaging indicating how to install / upgrade
Tested by building locally and seeing that the version prints itself and the CLI still runs
=> General improvements to CLI version management

package.json, src/plugins/aws/assumeRole.ts
Confirmed manually that a default region (us-west-2) and a non-default region (eu-south-1) both work with the regional endpoint.
=> Use regional STS endpoint

.prettierignore, package.json, src/commands/__tests__/login.test.ts, src/commands/index.ts, src/drivers/api.ts, src/drivers/auth/index.ts, src/index.ts, src/middlewares/version.ts, src/opentelemetry/buffered-exporter.ts, src/opentelemetry/instrumentation.ts, src/version.ts, yarn.lock
Add OpenTelemetry tracing and create a root span in `main`.
- The collector endpoint is an endpoint in the P0 backend, that is authenticated. This means we can only export spans _after_ the user has logged in.
- Add a custom `BufferedSpanExporter` exporter that just buffers spans in memory until login is complete and JWT is available to send in the header. In practice, we are not actually buffering spans yet since export is not triggered until after login is complete since we don't have enough spans yet. In practice export is triggered forcefully before CLI exits. Note that even if we omitted the buffering functionality we'd still need something like the `BufferedSpanExporter` that allows injecting the delegate `OTLPTraceExporter` after authentication is complete, because the …
=> OpenTelemetry tracing

src/commands/scp.ts, src/commands/shared/ssh.ts, src/plugins/ssh/index.ts
You can copy recursively using scp's native recursive (`-r` or `--recursive`) flag. P0's own flag is redundant and can be removed.
Here is a demonstration that the `-r` flag works when passed after `--`:
https://github.com/user-attachments/assets/4c90ab24-64ec-4b5a-bb37-856c8f8e79cb
=> Remove --recursive flag from scp command

src/commands/scp.ts, src/commands/shared/ssh.ts, src/commands/ssh-proxy.ts, src/commands/ssh-resolve.ts, src/commands/ssh.ts, src/drivers/api.ts, src/plugins/ssh/index.ts
**Problem**
Splunk wants audit logs for when sessions start to help keep track of who is using the p0 CLI.
**Change**
Adds support audit logging session start and end for `p0 ssh`, `p0 scp`, and `p0 ssh-proxy` commands
**Validation**
In conjunction with Backend service PR https://github.com/p0-security/app/pull/4029 use the SSH/SCP/SSH-PROXY commands and check that audit logs generate correct information.
Sample commands:
```
./p0 scp test.txt miguel-node-1:test.txt
./p0 ssh private-node --provider gcloud --sudo
ssh netfoundry-edge-router 
```
**Tracking**
https://linear.app/p0-security/issue/ENG-3248/capture-every-session-start
**Attachments**
---
---
---
=> Audit log ssh session start and end

src/commands/shared/index.ts
The error message from access request provisioning was not shown to the user.
Verified new behavior manually by triggering an error:
Before
```
p0cli % ./p0 ssh nano-node-1
Access requested (see https://... for details)
Will wait up to 5 minutes for this request to complete...
Your request was approved
Waiting for access to be provisioned
Your access request encountered an error (see Slack for details)
```
After - error message
```
p0cli % ./p0 ssh nano-node-1   
Access requested (see https://... for details)
Will wait up to 5 minutes for this request to complete...
Your request was approved
Waiting for access to be provisioned
Error in service aws: User: arn:aws:sts::123456789012:assumed-role/P0RoleIamManager/aws-sdk-js-session-123456789012 is not authorized to perform: ssm:SendCommand …
```
=> Show access request provisioning errors to user

esbuild.js, p0
When running the standalone CLI, I currently get a deprecation warning for 'punycode':
```
dhing@Mac p0cli % yarn build:macos && ./mac/build-macOS.sh 
yarn run v1.22.22
warning ../../package.json: No license field
$ tsc && cp -r public build/dist/ && node esbuild.js
Bundling succeeded.
✨  Done in 2.07s.
Wrote single executable preparation blob to ./build/sea/p0.blob
Start injection of NODE_SEA_BLOB in ./build/sea/p0...
💉 Injection done!
dhing@Mac p0cli % ./build/sea/p0 --version
(node:24002) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `p0 --trace-deprecation ...` to show where the warning was created)
0.18.8
```
I would like to silence these warnings so that end users don't see them, since they aren't actionable.
This …
=> Adjust warnings emitted by CLI

package.json, src/commands/__tests__/login.test.ts, src/commands/login.ts, src/commands/shared/request.ts, src/drivers/api.ts, src/drivers/auth/index.ts, src/types/identity.ts, src/types/org.ts
Adds a method for passing through the provider access_token to the API calls made, skipping firebase auth.
**Note:** firebase is still initialized + used for org discovery.
=> ENG 5461: Add auth passthrough mechanism

src/commands/__tests__/login.test.ts, src/drivers/api.ts, src/drivers/auth/path.ts, src/drivers/config.ts, src/drivers/env.ts, src/drivers/org.ts, src/util.ts
Adds the ability to configure the P0 CLI using an optional `bootstrap-<org id>.json` file that gets placed in the `~\.p0` directory. This alleviates the need to connect to P0 servers to load the org config.
=> ENG-5443 Add bootstrap org config

src/plugins/google/ssh-key.ts, src/util.ts
Fixes gcloud SSH on Windows machines. The problem is that on Windows, when installing the Google Cloud tools, the main `gcloud` file is a `.cmd` (shell script) file rather than a `.exe` (binary executable) file, so when calling `spawn`, it cannot be located.
That is because the underlying Windows OS API that `spawn` uses doesn't resolve `.CMD` files by default (MacOS does not have this problem because MacOS will automatically resolve "gcloud" to the correct executable).
Fix is when on a Windows machine to instead call `cmd.exe` with `gcloud.cmd` and the remaining parameters as args, which will resolve the correct file.
Validated that `gcloud` could be correctly resolved on:
=> Fix gcloud resolution on Windows

src/commands/ssh.ts
Current text:
"Flags and positionals passed to the underlying ssh implementation."
New text:
"Options passed to the underlying ssh implementation."
We don't currently support specifying positionals after `--`. Updated the description accordingly.
Specifically, the command to be executed is already an argument to `p0 ssh` and must be specified before the `--`.
=> ENG-5485 Update description of SSH args to explicitly specify options

src/commands/__tests__/__snapshots__/ssh.test.ts.snap, src/commands/shared/request.ts, src/commands/shared/ssh.ts, src/drivers/__tests__/api.test.ts, src/drivers/api.ts
Problem:
We do not handle stream api errors which fail during permission request creation. This is apparent when we try to ssh into a non-existent node.
1. the errors thrown by errorBoundary and unhandled error objects from the backend do not have "type" defined like streaming responses.
2. these errors are not new line delimited.
Change:
1. introduce way to debug these requests.
2. try parsing the leftover buffer and validate compelete-ness.
3. if the json is error, surface the error to the user.
Tracking:
ENG-5801
Commands:
the node should not exist
./p0 ssh dummy-node-123
./p0 ssh dummy-node-123 --debug
Attachements:
Before:
After:
=> Fix stream api handling of errors without type and new line

src/commands/shared/ssh.ts, src/commands/ssh-resolve.ts, src/drivers/api.ts, src/plugins/aws/ssh.ts, src/plugins/azure/keygen.ts, src/plugins/azure/ssh.ts, src/plugins/google/ssh.ts, src/plugins/self-hosted/keygen.ts, src/plugins/self-hosted/ssh.ts, src/plugins/ssh/index.ts, src/plugins/ssh/shared.ts, src/types/ssh.ts
**Problem**
Public keys are not as secure as certificates for SSH access.
**Change**
Implements automatic registration and short-lived certificate access.
**Validation**
1. Registration Process & changing a node's name.
2. Making an access request.
3. Connecting with tailscale on NixOS
**Tracking**
https://linear.app/p0-security/issue/ENG-5826/switch-to-short-lived-certificates-for-access
**Implementation**
1. We switched to automatic registration so that user's don't need to manually configure the node anymore, they just pass in the api key (which will switch to auth token)
2. We're saving the CA public key in the user's authorized_keys file, this makes it so that machines don't implicitly trust any signed certificate but allows us to selectively determine which machines a user has …
=> Switch to certificates for self-hosted SSH access

src/commands/shared/ssh.ts, src/commands/ssh-resolve.ts, src/common/__mocks__/keys.ts, src/common/keys.ts, src/plugins/aws/ssh.ts, src/plugins/aws/types.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
**Problem**
User's have to do host key validation even though they have instances managed by P0.
**Change**
This PR adds a new SSM document that we can run on target machines to retrieve dynamic registration information such as a server's host keys.
**Validation**
Tested in conjunction with the P0 APP PR: https://github.com/p0-security/app/pull/4314
Remove all my known host keys from my known host key file. Ensure that the prompt doesn't appear.
**Tracking**
https://linear.app/p0-security/issue/ENG-5884/validate-ssh-fingerprint-on-aws-machines
**Implementation**
I was thinking about accessing the host keys on the fly and doing it lazily, but in scenarios where customers are requesting access to 100's of nodes this creates a significant bottle neck in SSM.
=> Retrieve server host keys for AWS SSH

package.json, src/commands/shared/request.ts, src/commands/shared/ssh.ts, src/commands/ssh-resolve.ts
* Adds sudo support to ssh-resolve
* ssh-resolve will first attempt to request sudo access
* If that fails, it will fall back to requesting non-sudo access
=> ENG-5732 Add sudo support to ssh-resolve

src/plugins/google/ssh-key.ts, src/plugins/google/ssh.ts, src/plugins/google/util.ts
Fixes gcloud resolution for the proxy command.
Validated on: Windows 11 Pro, 24H2 on powershell and command prompt
Note: this can be thought of as a follow-up to #233. This makes the same change to the proxy command
=> Fix gcloud resolution for proxy command

package.json, src/commands/aws/index.ts, src/commands/aws/permission-set.ts, src/commands/aws/role.ts, src/commands/aws/types.ts, src/commands/kubeconfig.ts, src/commands/login.ts, src/commands/ls.ts, src/commands/shared/ssh.ts, src/common/retry.ts, src/drivers/api.ts, src/plugins/aws/config.ts, src/plugins/aws/idc/index.ts, src/plugins/aws/ssh.ts, src/plugins/azure/tunnel.ts, src/plugins/kubeconfig/index.ts, src/plugins/okta/aws.ts, src/plugins/ssh/index.ts, src/types/ssh.ts
Adds retries when the p0 backend returns a `429 Too Many Requests` error. The primary case when that can happen is executing `p0 ssh` or other commands from automated scripts that loop a number of instances.
Since these scripts themselves may be difficult to make fault-tolerant, this change adds internal retries to all calls to the p0 backend.
Changes to enable this:
- Improve `retryWithSleep` utility:
- Add arguments `multiplier`, to allow exponential backoff, and `debug` to allow printing retry information
- Turn argument list into `options` object with defaults
- Unify error handling on streaming and regular API call path with `parseResponseText`
Other changes:
- Add / remove space to have one space between words
- Make `tryParseHtmlError` to capture errors that originate from the …
=> Retry 429 HTTP errors

src/drivers/api.ts
Server returns a 400 response if CLI command is incomplete, 
which is not handled correctly after we added parsing of 429 errors.
* Always try to parse response as JSON first
* If not JSON, fall back to parse HTTP status codes
=> ENG-6129 Correctly handle 400 response

src/commands/index.ts, src/drivers/auth/index.ts, src/index.ts, src/middlewares/version.ts, src/util.ts
On Windows, the NPM version check was broken, which led to the end user sometimes needing to run the login command twice. This fixes the core issues at play, but also improves debug logging for easier traceability.
- Adjusts the spawn of the NPM version check to account for the fact that NPM isn't a .exe file.
- Adds a .on("error") check to the `exec` implementation to explicitly handle errors (required to prevent uncaught exceptions)
- Adds global process error handlers to improve logging when uncaught errors or unhandled rejections occur (without this change, nothing printed to the terminal; with this change, it would have made it much easier to debug this particular issue)
- Improves overall debug logging of the NPM version checking code paths
- Adjusts `.on("exit")` to `.on("close")` …
=> Fix CLI double login bug, improve debug logging

src/plugins/ssh/index.ts
Set default MACs on Windows when using `p0 ssh`. One of the MACs that OpenSSH on Windows ships with (`umac-128-etm@openssh.com`) appears to work unreliably, and using it may lead to a "Corrupted MAC on input" error. With this change, `p0 ssh <instance>` on Windows will only choose one of our specified MACs by default: `hmac-sha2-256-etm@openssh.com` or `hmac-sha2-256`.
Notes:
- the user can still explicitly specify a different MAC if they prefer by running `p0 ssh <instance> -- -o MACs=<other mac>`, which will override these defaults
- if the user explicitly specifies the broken MAC by running `p0 ssh <instance> -- -o MACs=umac-128-etm@openssh.com`, this will override our defaults and they will still see the Corrupted MAC error
- the ETM variant is more secure than the plain HMAC, so it …
=> Manually specify SSH MAC algorithms on Windows

src/commands/shared/ssh.ts, src/plugins/google/ssh-key.ts, src/plugins/google/ssh.ts, src/types/ssh.ts
This change fixes a bug where in some circumstances, the request object won't contain a public key due to the manner in which it was originally requested. In those situations, the public key won't get imported into the user's Google account, preventing them from SSH-ing into gcloud VMs.
This change resolves this issue by instead using whichever SSH public key is currently on the user's machine (in the `~/.p0/ssh` folder).
Additionally, to improve error handling by failing more quickly, `importSshKey` throws if the public key is missing.
=> Gcloud SSH: Fallback to local SSH public key for OS Login Import
