package.json
Bumps the minor version for our latest release which includes a breaking change for eventually supporting making an access request for a group of nodes.
=> Update package to 0.4.1

package.json
This PR updates the `package.json` to version 0.4.2 for our latest release.
=> Update package to 0.4.2

src/commands/__tests__/ssh.test.ts, src/commands/aws/__tests__/role.test.ts, src/commands/aws/role.ts, src/plugins/aws/config.ts, src/plugins/aws/types.ts, src/plugins/okta/aws.ts, src/plugins/okta/login.ts
P0's data model for AWS installations has changed. Update the CLI to work with this new data model.
=> aws: Update for new install data model

src/commands/__tests__/__snapshots__/ls.test.ts.snap, src/commands/ls.ts
Addresses ENG-1608. Marks accessible resources with * in ls results and shows them at the top.
Depends on PR https://github.com/p0-security/app/pull/1537/
Example output:
=> ls: Show accessible resources

src/plugins/kubeconfig/index.ts, src/plugins/kubeconfig/types.ts
Updates the K8s Integration Installation document check.
=> K8s Generic Install

package.json
=> Update patch version for k8s generic install document

src/plugins/google/ssh-key.ts
The CLI sometimes fails with this error:
```
TypeError: Cannot read properties of undefined (reading 'posixAccounts')
at /opt/homebrew/lib/node_modules/@p0security/cli/dist/plugins/google/ssh-key.js:69:40
at Generator.next (<anonymous>)
at fulfilled (/opt/homebrew/lib/node_modules/@p0security/cli/dist/plugins/google/ssh-key.js:5:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
It seems related to gcloud login, even though "gcloud auth print-access-token" either prints a token or otherwise returns with exit code 0.
It is possible that there is a corner case here where gcloud returns an expired access token.
Since exit code 0 is returned, we continue to upload the SSH public key, which then silently fails, leading to the subsequent error.
Fix: Validate …
=> ENG-2449 Add error handling for importSshPublicKey call

src/plugins/aws/ssh.ts, src/plugins/ssh/index.ts
Prints an error message if SSH fails to establish a connection.
=> ENG-2768 Print an error message if SSH fails to establish a connection

src/plugins/ssh/index.ts
Revert "ENG-2768 Print an error message if SSH fails to establish a connection (#127)"
This reverts commit f3f18bfcb011bfbfcec478172614471ae2b94497.
=> ENG-2784 Revert printing of SSH failure message

package.json
Updates the current package version to release latest changes.
=> Release v0.13.1

package.json
=> Bump version to 0.13.4

src/commands/shared/index.ts, src/commands/shared/request.ts, src/commands/shared/ssh.ts, src/plugins/kubeconfig/index.ts, src/types/request.ts, src/types/ssh.ts
- Show a detailed message in case of an error
- Rename Request type to PermissionRequest
- Add optional error field to PermissionRequest
=> ENG-3851 Output detailed error message

src/commands/ls.ts
Enables --json object to directly output json response from backend
=> p0 ls Machine readable output

package.json
=> Version 15

package.json, src/commands/ls.ts
Print output to stdout instead of stderr when --json flag is passed
=> JSON output to stdout not stderr

package.json, src/commands/__tests__/login.test.ts, src/commands/index.ts, src/commands/shared/ssh.ts, src/commands/ssh-resolve.ts, src/drivers/config.ts, src/drivers/env.ts, src/drivers/firestore.ts, src/index.ts, src/plugins/azure/auth.ts, src/plugins/ssh/index.ts, src/types/org.ts, src/util.ts
Provide a configurable contact/help message so that we can provide a custom message to tenants if needed.
=> ENG-2713 Make the contact/help message configurable

src/commands/scp.ts, src/commands/ssh-proxy.ts, src/commands/ssh-resolve.ts, src/commands/ssh.ts, src/drivers/auth/index.ts, src/drivers/firestore.ts, src/drivers/util.ts
Catch and handle authentication errors:
* Inform end-user of stale/invalid token errors
* Provide a public help message for unexpected auth errors
=> ENG-4641 Catch and handle authentication errors

src/plugins/ssh/index.ts
Terminate the SSH child process when the P0 CLI parent process terminates.
Tested using SIGHUP and SIGQUIT.
=> ENG-4759 Terminate SSH child process

package.json
=> Bump version to 0.18.5

src/commands/kubeconfig.ts
Add code comment to keep backend and CLI in sync
=> Kubeconfig warning comment

package.json
PR primarily to get a Windows release out, but will also include these changes since the previous release:
* Remove --recursive flag from scp command by @gergas3 in https://github.com/p0-security/p0cli/pull/216
* Remove ssh key-gen command by @gergas3 in https://github.com/p0-security/p0cli/pull/217
* Audit log ssh session start and end by @GGonryun in https://github.com/p0-security/p0cli/pull/214
* Show access request provisioning errors to user by @gergas3 in https://github.com/p0-security/p0cli/pull/218
Will open a new release following this merge.
=> Bump to v0.18.8

src/drivers/api.ts
The WAF of the P0 backend returns error messages as an HTML page.
These error messages were not surfaced to the user, instead the CLI failed parsing them as JSON and surfaced that error.
Changes:
- First check if the response is in the format that the WAF returns: contains a <title> tag with the status code in it. If yes, return that as an error message. If no, continue with parsing as JSON.
- Opportunistic change: refactor `baseFetch` and `unauthenticatedFetch` to use a common base function - which is called `baseFetch`. The net result is that `unauthenticatedFetch` becomes `baseFetch` because authentication is an additional header on top of the base request format. So the old `baseFetch` the becomes `authFetch`.
=> Friendly error message for errors from web application firewall

package.json
Releases the following changes:
- https://github.com/p0-security/p0cli/pull/243
- https://github.com/p0-security/p0cli/pull/223
- https://github.com/p0-security/p0cli/pull/239
=> v0.18.11 release

package.json
=> Bump version to 0.19.1

src/commands/login.ts, src/drivers/auth/index.ts, src/drivers/config.ts, src/drivers/firestore.ts
We would like to have better visibility into the login flow when running `p0 login` and the `--debug` flag is added.
=> Add some logging for improved visibility into login flow

package.json
Release for https://github.com/p0-security/p0cli/pull/259
=> Bump version to 0.19.3

package.json
Update the P0 CLI version to 0.19.4.
=> Update the P0 CLI version to 0.19.4
